In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')
from sklearn.preprocessing import Normalizer

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])
print(dataset.isnull().sum())

from sklearn.preprocessing import Normalizer ,LabelEncoder
le=LabelEncoder()
le.fit_transform(dataset['cholesterol'])
#dataset.cholesterol(le.fit_transform)
print(dataset.cholesterol.values)
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)

age                    0
sex                    0
chest pain type        0
resting bp s           0
cholesterol            0
fasting blood sugar    0
resting ecg            0
max heart rate         0
exercise angina        0
oldpeak                0
ST slope               0
target                 0
dtype: int64
[289 180 283 ... 131 236 175]


In [ ]:
AaaaaAaaAaAaaaazAAaAAaAAAzaAaaaaaaaAaaAZZASaaAAaAaazAAaaAaAaaaaAaAaaAaaAAASAASaaaAaZAASAAASAaaaaaaaaaaaaAaAaaaaaaaaAAaaAAAAaAAAAAAaaAAA!!!!!!!!Z‌‌##dataset

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)


(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
model=dt.fit(x_train_data,y_train_data)
prediction=model.predict(x_test_data)

#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))

[[ 82  11]
 [ 17 128]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.85        93
           1       0.92      0.88      0.90       145

    accuracy                           0.88       238
   macro avg       0.87      0.88      0.88       238
weighted avg       0.88      0.88      0.88       238



NameError: ignored

In [ ]:
from sklearn.preprocessing import normalizer
scaler=normalizer().fit(x)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)


(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
#Random Forest Classifier
from sklearn.ensemble  import RandomForestClassifier
rf=RandomForestClassifier()
model=rf.fit(x_train_data,y_train_data)
prediction=model.predict(x_test_data)

#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[ 85   8]
 [  6 139]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92        93
           1       0.95      0.96      0.95       145

    accuracy                           0.94       238
   macro avg       0.94      0.94      0.94       238
weighted avg       0.94      0.94      0.94       238



In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)

(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
#Random SVM Classifier
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear', random_state=0) 
model=svclassifier.fit(x_train_data,y_train_data.values.ravel())
prediction=model.predict(x_test_data)

#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))

[[ 77  16]
 [ 18 127]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        93
           1       0.89      0.88      0.88       145

    accuracy                           0.86       238
   macro avg       0.85      0.85      0.85       238
weighted avg       0.86      0.86      0.86       238



In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)


(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB  
naiveclassifier = GaussianNB()  
model=naiveclassifier.fit(x_train_data,y_train_data.values.ravel())
prediction=model.predict(x_test_data)

#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))


[[ 77  16]
 [ 24 121]]
              precision    recall  f1-score   support

           0       0.76      0.83      0.79        93
           1       0.88      0.83      0.86       145

    accuracy                           0.83       238
   macro avg       0.82      0.83      0.83       238
weighted avg       0.84      0.83      0.83       238



In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)

(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
#descision tree
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
model=dt.fit(x_train_data,y_train_data)
prediction=model.predict(x_test_data)

#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))


[[ 81  12]
 [ 20 125]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84        93
           1       0.91      0.86      0.89       145

    accuracy                           0.87       238
   macro avg       0.86      0.87      0.86       238
weighted avg       0.87      0.87      0.87       238



In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)

(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gradiant=GradientBoostingClassifier()

model=gradiant.fit(x_train_data,y_train_data.values.ravel())
prediction=model.predict(x_test_data)


#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))

[[ 77  16]
 [ 18 127]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        93
           1       0.89      0.88      0.88       145

    accuracy                           0.86       238
   macro avg       0.85      0.85      0.85       238
weighted avg       0.86      0.86      0.86       238



In [ ]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('/content/drive/MyDrive/heart_statlog_cleveland_hungary_final.csv')

x=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
x_data=scaler.transform(x)
from sklearn.model_selection import train_test_split
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x,y,test_size=0.2,random_state=123)

print(x_train_data.shape,y_train_data.shape,x_test_data.shape,y_test_data.shape)

(952, 11) (952, 1) (238, 11) (238, 1)


In [ ]:
from sklearn.linear_model import LogisticRegression  

logistic=LogisticRegression()

model=logistic.fit(x_train_data,y_train_data.values.ravel())
prediction=model.predict(x_test_data)


#confusion matrix
from sklearn.metrics import  classification_report,confusion_matrix,accuracy_score
cm=confusion_matrix(y_test_data,prediction)
print(cm)

print(classification_report(y_test_data,prediction))

[[ 77  16]
 [ 26 119]]
              precision    recall  f1-score   support

           0       0.75      0.83      0.79        93
           1       0.88      0.82      0.85       145

    accuracy                           0.82       238
   macro avg       0.81      0.82      0.82       238
weighted avg       0.83      0.82      0.82       238



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
